-- Create Tables for Hospital Database System (Oracle Compatible)

-- 1. Independent Tables (No Foreign Keys)

CREATE TABLE Country (
    country_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    country_name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (country_id),
    CONSTRAINT uq_country_name UNIQUE (country_name)
);

CREATE TABLE Province (
    province_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    province_name VARCHAR2(100) NOT NULL,
    country_id NUMBER NOT NULL,
    CONSTRAINT pk_province PRIMARY KEY (province_id),
    CONSTRAINT fk_province_country FOREIGN KEY (country_id) REFERENCES Country(country_id)
    ON DELETE CASCADE
);

CREATE TABLE District (
    district_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    district_name VARCHAR2(100) NOT NULL,
    province_id NUMBER NOT NULL,
    CONSTRAINT pk_district PRIMARY KEY (district_id),
    CONSTRAINT fk_district_province FOREIGN KEY (province_id) REFERENCES Province(province_id) ON DELETE CASCADE
);

CREATE TABLE Neighbourhood (
    neighbourhood_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    neighbourhood_name VARCHAR2(100) NOT NULL,
    district_id NUMBER NOT NULL,
    postal_code VARCHAR2(20),
    CONSTRAINT pk_neighbourhood PRIMARY KEY (neighbourhood_id),
    CONSTRAINT fk_neighbourhood_district FOREIGN KEY (district_id) REFERENCES District(district_id) ON DELETE CASCADE
);

CREATE TABLE Address (
    address_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    neighbourhood_id NUMBER NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (address_id),
    CONSTRAINT fk_address_neighbourhood FOREIGN KEY (neighbourhood_id) REFERENCES Neighbourhood(neighbourhood_id) ON DELETE CASCADE
);

CREATE TABLE Blood_Type (
    blood_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    type_name VARCHAR2(10) NOT NULL,
    CONSTRAINT pk_blood PRIMARY KEY (blood_id),
    CONSTRAINT uq_blood_type_name UNIQUE (type_name),
    CONSTRAINT chk_blood_type_name CHECK(type_name IN ('B+', 'B-', 'A+', 'A-', 'AB+', 'AB-', 'O+', 'O-'))
);

CREATE TABLE ICD10 (
    icd10_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    icd10_code VARCHAR2(20) NOT NULL,
    description CLOB,
    CONSTRAINT pk_icd10 PRIMARY KEY (icd10_id),
    CONSTRAINT uq_icd10_code UNIQUE (icd10_code)
);

CREATE TABLE Job_Status (
    job_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    status_name VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_job_status PRIMARY KEY (job_status_id),
    CONSTRAINT uq_job_status_name UNIQUE (status_name),
    CONSTRAINT chk_job_status_name CHECK(status_name IN ('RETIRED', 'OFFDUTY', 'ACTIVE', 'FIRED'))
);

CREATE TABLE Specialization (
    spec_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    spec_name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_specialization PRIMARY KEY (spec_id),
    CONSTRAINT uq_spec_name UNIQUE (spec_name)
);

CREATE TABLE Payment_Method (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    type_name VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_payment_method PRIMARY KEY (payment_id),
    CONSTRAINT uq_payment_type_name UNIQUE (type_name)
);

CREATE TABLE Schedule (
    schedule_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    schedule_date DATE NOT NULL,
    schedule_time TIMESTAMP NOT NULL,
    CONSTRAINT pk_schedule PRIMARY KEY (schedule_id)
);

CREATE TABLE Emergency_Person (
    emergency_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    emg_first_name VARCHAR2(50) NOT NULL,
    emg_last_name VARCHAR2(50) NOT NULL,
    emg_phone_no VARCHAR2(20) NOT NULL,
    emg_gender CHAR(1) NOT NULL,
    CONSTRAINT chk_emg_gender CHECK (emg_gender IN ('M', 'F')),
    CONSTRAINT pk_emergency_person PRIMARY KEY (emergency_id),
    CONSTRAINT uq_emg_phone_no UNIQUE (emg_phone_no)
);

-- 2. Dependent Tables (With Foreign Keys)

-- Doctor Table
CREATE TABLE Doctor (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    doc_first_name VARCHAR2(50) NOT NULL,
    doc_last_name VARCHAR2(50) NOT NULL,
    doc_birth_date DATE NOT NULL,
    office_number VARCHAR2(20),
    doc_phone_no VARCHAR2(20) NOT NULL,
    doc_email VARCHAR2(100) NOT NULL,
    doc_gender CHAR(1) NOT NULL,
    is_married NUMBER(1), -- 1 for True, 0 for False
    job_status_id NUMBER NOT NULL,
    address_id NUMBER NOT NULL,
    dept_id NUMBER, -- To be handled via ALTER due to circular dependency with Department head_doctor
    CONSTRAINT pk_doctor PRIMARY KEY (doctor_id),
    CONSTRAINT uq_doc_phone_no UNIQUE (doc_phone_no),
    CONSTRAINT uq_doc_email UNIQUE (doc_email),
    CONSTRAINT chk_doc_gender CHECK (doc_gender IN ('M', 'F')),
    CONSTRAINT fk_doctor_job_status FOREIGN KEY (job_status_id) REFERENCES Job_Status(job_status_id),
    CONSTRAINT fk_doctor_address FOREIGN KEY (address_id) REFERENCES Address(address_id)
);

-- Department Table (Requires Doctor for head_doctor)
CREATE TABLE Department (
    dept_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    dept_name VARCHAR2(100) NOT NULL,
    dept_phone_no VARCHAR2(20) NOT NULL,
    dept_description CLOB,
    head_doctor NUMBER,
    CONSTRAINT pk_department PRIMARY KEY (dept_id),
    CONSTRAINT uq_dept_name UNIQUE (dept_name),
    CONSTRAINT uq_dept_phone_no UNIQUE (dept_phone_no),
    CONSTRAINT uq_dept_head_doctor UNIQUE (head_doctor),
    CONSTRAINT fk_department_head_doctor FOREIGN KEY (head_doctor) REFERENCES Doctor(doctor_id) ON DELETE SET NULL
);

-- Add dept_id to Doctor (1:N relationship from Department to Doctor)
ALTER TABLE Doctor ADD CONSTRAINT fk_doctor_department FOREIGN KEY (dept_id) REFERENCES Department(dept_id) ON DELETE SET NULL;

-- Patient Table
CREATE TABLE Patient (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pat_first_name VARCHAR2(50) NOT NULL,
    pat_last_name VARCHAR2(50) NOT NULL,
    pat_birth_date DATE NOT NULL,
    pat_gender CHAR(1) NOT NULL,
    pat_phone_no VARCHAR2(20) NOT NULL,
    pat_email VARCHAR2(100) NOT NULL,
    blood_id NUMBER NOT NULL,
    address_id NUMBER NOT NULL,
    CONSTRAINT pk_patient PRIMARY KEY (patient_id),
    CONSTRAINT uq_pat_phone_no UNIQUE (pat_phone_no),
    CONSTRAINT uq_pat_email UNIQUE (pat_email),
    CONSTRAINT chk_pat_gender CHECK (pat_gender IN ('M', 'F')),
    CONSTRAINT fk_patient_blood FOREIGN KEY (blood_id) REFERENCES Blood_Type(blood_id),
    CONSTRAINT fk_patient_address FOREIGN KEY (address_id) REFERENCES Address(address_id)
);

-- Doctor - Schedule (Availability/Assignment)
CREATE TABLE Doctor_Schedule (
    doctor_id NUMBER NOT NULL,
    schedule_id NUMBER NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_doctor_schedule PRIMARY KEY (doctor_id, schedule_id),
    CONSTRAINT fk_doc_sch_doctor FOREIGN KEY (doctor_id) REFERENCES Doctor(doctor_id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_sch_schedule FOREIGN KEY (schedule_id) REFERENCES Schedule(schedule_id) ON DELETE CASCADE
);

-- Appointment Table
CREATE TABLE Appointment (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    schedule_id NUMBER NOT NULL,
    CONSTRAINT pk_appointment PRIMARY KEY (appointment_id),
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES Patient(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_doc_sch FOREIGN KEY (doctor_id, schedule_id) REFERENCES Doctor_Schedule(doctor_id, schedule_id) ON DELETE CASCADE,
    CONSTRAINT uq_appointment_doc_sch UNIQUE (doctor_id, schedule_id)
);

-- Treatment Table
CREATE TABLE Treatment (
    treatment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    appointment_id NUMBER NOT NULL,
    icd10_id NUMBER NOT NULL,
    CONSTRAINT pk_treatment PRIMARY KEY (treatment_id),
    CONSTRAINT fk_treatment_appointment FOREIGN KEY (appointment_id) REFERENCES Appointment(appointment_id) ON DELETE CASCADE,
    CONSTRAINT fk_treatment_icd10 FOREIGN KEY (icd10_id) REFERENCES ICD10(icd10_id) ON DELETE CASCADE
);

-- Bill Table
CREATE TABLE Bill (
    treatment_id NUMBER,
    total_amount NUMBER(10, 2) NOT NULL,
    tax NUMBER(10, 2) NOT NULL,
    payment_id NUMBER,
    is_paid NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_bill PRIMARY KEY (treatment_id),
    CONSTRAINT chk_bill_total_amount CHECK (total_amount >= 0),
    CONSTRAINT chk_bill_tax CHECK (tax >= 0),
    CONSTRAINT fk_bill_treatment FOREIGN KEY (treatment_id) REFERENCES Treatment(treatment_id) ON DELETE CASCADE,
    CONSTRAINT fk_bill_payment_method FOREIGN KEY (payment_id) REFERENCES Payment_Method(payment_id) ON DELETE SET NULL
);

-- Allergy Table
CREATE TABLE Allergy (
    allergy_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    icd10_id NUMBER NOT NULL,
    CONSTRAINT pk_allergy PRIMARY KEY (allergy_id),
    CONSTRAINT uq_allergy_icd10 UNIQUE (icd10_id),
    CONSTRAINT fk_allergy_icd10 FOREIGN KEY (icd10_id) REFERENCES ICD10(icd10_id) ON DELETE CASCADE
);

-- 3. Many-to-Many (M:N) Relationship Junction Tables

-- Doctor - Specialization
CREATE TABLE Doctor_Specialization (
    doctor_id NUMBER NOT NULL,
    spec_id NUMBER NOT NULL,
    CONSTRAINT pk_doctor_specialization PRIMARY KEY (doctor_id, spec_id),
    CONSTRAINT fk_doc_spec_doctor FOREIGN KEY (doctor_id) REFERENCES Doctor(doctor_id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_spec_specialization FOREIGN KEY (spec_id) REFERENCES Specialization(spec_id) ON DELETE CASCADE
);

-- Patient - Allergy
CREATE TABLE Patient_Allergy (
    patient_id NUMBER NOT NULL,
    allergy_id NUMBER NOT NULL,
    CONSTRAINT pk_patient_allergy PRIMARY KEY (patient_id, allergy_id),
    CONSTRAINT fk_pat_allergy_patient FOREIGN KEY (patient_id) REFERENCES Patient(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_pat_allergy_allergy FOREIGN KEY (allergy_id) REFERENCES Allergy(allergy_id) ON DELETE CASCADE
);

-- Patient - Emergency Person
CREATE TABLE Patient_Emergency_Person (
    patient_id NUMBER NOT NULL,
    emergency_id NUMBER NOT NULL,
    CONSTRAINT pk_patient_emergency_person PRIMARY KEY (patient_id, emergency_id),
    CONSTRAINT fk_pat_emg_patient FOREIGN KEY (patient_id) REFERENCES Patient(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_pat_emg_emergency FOREIGN KEY (emergency_id) REFERENCES Emergency_Person(emergency_id) ON DELETE CASCADE
);
